### ISSUE TITLE
Initial TODOs

### ISSUE THREAD

**Issue by cberys** [hackthackathon/llm4hack#1]
## TODO

- [x]  GitHub project
- [x]  Convert to markdown
- [ ]  Guidelines for participants
- [ ]  Guidelines for organizers
- [ ]  Flesh out content
- [ ]  Invite comments and discussion
- [ ]  Paper
